package web591

// Generated by https://quicktype.io

type HomeDetail struct {
	Data   HomeDetailData `json:"data"`
	Msg    string         `json:"msg"`
	Status int64          `json:"status"`
}

type HomeDetailData struct {
	Breadcrumb    []Breadcrumb  `json:"breadcrumb"`
	Browse        Browse        `json:"browse"`
	CostData      CostData      `json:"costData"`
	DealText      string        `json:"dealText"`
	DealTime      int64         `json:"dealTime"`
	Deposit       string        `json:"deposit"`
	FavData       FavData       `json:"favData"`
	HouseDetail   HouseDetail   `json:"houseDetail"`
	Info          []Info        `json:"info"`
	InfoData      InfoData      `json:"infoData"`
	Kind          int64         `json:"kind"`
	LinkInfo      LinkInfo      `json:"linkInfo"`
	NavData       []HouseDetail `json:"navData"`
	PositionRound PositionRound `json:"positionRound"`
	Preference    CostData      `json:"preference"`
	Price         string        `json:"price"`
	PriceCache    []interface{} `json:"priceCache"`
	PriceCacheTxt string        `json:"priceCacheTxt"`
	PriceUnit     string        `json:"priceUnit"`
	Publish       Publish       `json:"publish"`
	QuestionData  HouseDetail   `json:"questionData"`
	RegionID      int64         `json:"regionId"`
	Relieved      int64         `json:"relieved"`
	Remark        HouseDetail   `json:"remark"`
	Rooms         HouseDetail   `json:"rooms"`
	SectionID     int64         `json:"sectionId"`
	Service       Service       `json:"service"`
	ShareInfo     ShareInfo     `json:"shareInfo"`
	Tags          []Tag         `json:"tags"`
	Title         string        `json:"title"`
}

type Breadcrumb struct {
	ID    int64  `json:"id"`
	Link  string `json:"link"`
	Name  string `json:"name"`
	Query string `json:"query"`
}

type Browse struct {
	Mobile int64 `json:"mobile"`
	PC     int64 `json:"pc"`
}

type CostData struct {
	Active   int64   `json:"active"`
	Data     []Info  `json:"data"`
	Title    string  `json:"title"`
	Footnote *string `json:"footnote,omitempty"`
}

type Info struct {
	Key   string `json:"key"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

type FavData struct {
	Address  string `json:"address"`
	Area     string `json:"area"`
	Count    int64  `json:"count"`
	KindTxt  string `json:"kindTxt"`
	Layout   string `json:"layout"`
	Posttime int64  `json:"posttime"`
	Price    int64  `json:"price"`
	Thumb    string `json:"thumb"`
	Title    string `json:"title"`
}

type HouseDetail struct {
	Active  int64         `json:"active"`
	Key     string        `json:"key"`
	Title   string        `json:"title"`
	Content *string       `json:"content,omitempty"`
	Data    []interface{} `json:"data"`
}

type InfoData struct {
	Active         int64           `json:"active"`
	Data           []InfoDataDatum `json:"data"`
	HasCertificate int64           `json:"hasCertificate"`
	Title          string          `json:"title"`
}

type InfoDataDatum struct {
	Alias string `json:"alias"`
	Cate  int64  `json:"cate"`
	Key   string `json:"key"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

type LinkInfo struct {
	Avatar            string        `json:"avatar"`
	CertificateStatus int64         `json:"certificateStatus"`
	CertificateTxt    string        `json:"certificateTxt"`
	ChargeTxt         string        `json:"chargeTxt"`
	IMName            string        `json:"imName"`
	IMUid             int64         `json:"imUid"`
	IsTransferTel     int64         `json:"isTransferTel"`
	Line              string        `json:"line"`
	Mobile            string        `json:"mobile"`
	Name              string        `json:"name"`
	Phone             string        `json:"phone"`
	RentNum           int64         `json:"rentNum"`
	Role              int64         `json:"role"`
	RoleName          string        `json:"roleName"`
	RoleTxt           string        `json:"roleTxt"`
	SaleNum           int64         `json:"saleNum"`
	ShopID            int64         `json:"shopId"`
	ShopStatus        int64         `json:"shopStatus"`
	ShopVolume        int64         `json:"shopVolume"`
	SkillCases        []interface{} `json:"skillCases"`
	SkillWork         []interface{} `json:"skillWork"`
	Tips              string        `json:"tips"`
	Uid               int64         `json:"uid"`
	Warnmsg           int64         `json:"warnmsg"`
}

type PositionRound struct {
	Active        int64                `json:"active"`
	Address       string               `json:"address"`
	CommunityID   int64                `json:"communityId"`
	CommunityName string               `json:"communityName"`
	Data          []PositionRoundDatum `json:"data"`
	Key           string               `json:"key"`
	Lat           string               `json:"lat"`
	Lng           string               `json:"lng"`
	MapData       []MapDatum           `json:"mapData"`
	Title         string               `json:"title"`
}

type PositionRoundDatum struct {
	Children []DatumChild `json:"children"`
	Key      string       `json:"key"`
	Name     string       `json:"name"`
}

type DatumChild struct {
	Distance    int64  `json:"distance"`
	DistanceTxt string `json:"distanceTxt"`
	Name        string `json:"name"`
	Type        string `json:"type"`
}

type MapDatum struct {
	Children []MapDatumChild `json:"children"`
	Key      string          `json:"key"`
	Name     string          `json:"name"`
}

type MapDatumChild struct {
	Children []ChildChild `json:"children"`
	Key      string       `json:"key"`
	Name     string       `json:"name"`
}

type ChildChild struct {
	Distance            int64  `json:"distance"`
	Lat                 string `json:"lat"`
	Lng                 string `json:"lng"`
	Name                string `json:"name"`
	TradingAreaDistance int64  `json:"trading_area_distance"`
	TradingAreaID       int64  `json:"trading_area_id"`
}

type Publish struct {
	ID         int64  `json:"id"`
	Key        string `json:"key"`
	Name       string `json:"name"`
	PostTime   string `json:"postTime"`
	UpdateTime string `json:"updateTime"`
}

type Service struct {
	Active   int64      `json:"active"`
	Desc     string     `json:"desc"`
	Facility []Facility `json:"facility"`
	Key      string     `json:"key"`
	Rule     string     `json:"rule"`
	Title    string     `json:"title"`
}

type Facility struct {
	Active int64  `json:"active"`
	Key    string `json:"key"`
	Name   string `json:"name"`
}

type ShareInfo struct {
	From  string `json:"from"`
	Title string `json:"title"`
	URL   string `json:"url"`
}

type Tag struct {
	ID    int64  `json:"id"`
	Value string `json:"value"`
}
